services:
  - type: web
    name: usquests-backend
    env: python
    buildCommand: uv pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      # You need to define these manually in the Render dashboard:
      # - key: FIREBASE_SERVICE_ACCOUNT_KEY
      # - key: CRON_SECRET
